name: Build-Windows

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      core_version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          version: '6.8.3'

      - name: Configure
        run: >
          cmake
          -B build
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          "-DAPP_VERSION=${{ inputs.version }}"

      - name: Build
        run: cmake --build build --config Release --target CubedLauncher

      - name: Deploy Qt
        shell: cmd
        run: |
          windeployqt --release --qmldir qml build\CubedLauncher\CubedLauncher.exe

      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress

      - name: Build Installer
        shell: cmd
        run: |
          iscc /DCubedLauncherVersion=${{ inputs.version }} /DCubedLauncherFileVersion=${{ inputs.core_version }}.0 installer\installer.iss

      - name: Create Portable Zip
        shell: pwsh
        run: |
          Compress-Archive `
            -Path build/CubedLauncher/* `
            -DestinationPath CubedLauncher-${{ inputs.version }}-windows-x64-portable.zip

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            installer/output/*.exe
            *.zip
